-- Permet de lancer les commandes en un seul bloc, s'il y a une erreur alors toutes les commandes précédentes sont annulées
BEGIN;
-- Permet de réinitaliser à 0 nos tables dans la base de donnée
DROP TABLE IF EXISTS "user", "ticket", "tariff", "category", "activity", "image";

CREATE TABLE IF NOT EXISTS "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lastname" TEXT NOT NULL,
  "firstname" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'client',
  "email"  TEXT UNIQUE,
  "password" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ

);

CREATE TABLE IF NOT EXISTS "tariff" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "price" INTEGER NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
    
);

CREATE TABLE IF NOT EXISTS "ticket" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" DATE NOT NULL,
  "id_tariff" INTEGER NOT NULL REFERENCES "tariff"("id"),
  "id_user" INTEGER NOT NULL REFERENCES "user"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ

);
CREATE TABLE IF NOT EXISTS "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ

);
CREATE TABLE IF NOT EXISTS "activity" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "description" TEXT,
  "id_category" INTEGER NOT NULL REFERENCES "category"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
    
);
CREATE TABLE IF NOT EXISTS "image" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "link" TEXT NOT NULL UNIQUE,
  "id_activity" INTEGER NOT NULL REFERENCES "activity"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

-- Permet de ne pas avoir d'erreur s'il y a des accents dans la base de donnée (windows)
set client_encoding to 'utf8';

-- Arrêt du bloc de commandes
COMMIT;